#TODO
version: '3'

services:
  app:
    build: .
    environment:
      REDIS_HOST: redis
  redis:
    image: bitnami/redis:5.0.12
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'

